# Acredito que funcione agora a chave SSH, a chave privada (.pem) foi colocada no GitHub Secrets 
# e a publica foi colocada no final do arquivo authorized_keys da EC2
# outro teste pois acabei usando o docker compose down ao inves de docker compose stop
name: CI/CD Pipeline - SonarQube + OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # histórico completo - SonarQube usa isso para detectar codigo novo/alterado

      - name: Install SonarQube Scanner
        run: |
          curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.7.0.2747-linux sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
            -Dsonar.login=${{ secrets.SONAR_LOGIN }}

  owasp-zap-scan:
    name: OWASP ZAP Baseline Scan
    needs: sonarqube-analysis   # só roda se o job do SonarQube passar
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write            # a action abre e atualiza uma issue no repo com os alertas encontrados
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://18.229.232.47:3000'
          fail_action: false   # nao derruba o pipeline por causa dos alertas (mudar para true se qquiser bloquear o merge)
